platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 0.10.0'
pod 'SBJson', '~> 3.2'
pod 'PunchScrollView', '~> 1.0.2'
pod 'TestFlightSDK', '~> 2.0'
pod 'FlurrySDK', '~> 4.2.3'
pod 'SDWebImage', '~> 3.5'
pod 'Canvas', '~> 0.1'
pod 'Reachability', '~> 3.1.1'
pod 'AFNetworking', '~> 2.0.3'
